job_portal_final/urls.py
from django.contrib import admin
from django.urls import path, include
import pages.views as pages_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', pages_views.home_view, name='home'),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import *
from .views import *

app_name = 'users'
urlpatterns = [
    path('signup', signup_view, name='signup'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('change-email', change_email_view, name='change_email'),
    path('change-password', auth_views.PasswordChangeView.as_view(
        template_name='users/change_password.html',
        success_url='change-password/done',
        form_class=CustomPasswordChangeForm,
    ), name='change_password'),
    path('change-password/done', auth_views.PasswordChangeDoneView.as_view(template_name='users/change_password_done.html'), name='change_password_done'),
    path('reset-password', auth_views.PasswordResetView.as_view(
        template_name='users/reset_password.html',
        email_template_name='users/reset_password_email.html',
        success_url='reset-password/done',
        form_class=CustomPasswordResetForm,
    ), name='reset_password'),
    path('reset-password/done', auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_done.html'), name='reset_password_done'),
    path('reset-password-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/reset_password_confirm.html',
        success_url='/users/reset-password-complete',
        form_class=CustomSetPasswordForm,
    ), name='reset_password_confirm'),
    path('reset-password-complete', auth_views.PasswordResetCompleteView.as_view(template_name='users/reset_password_complete.html'), name='reset_password_complete'),
]

templates/navbar/admin_navbar.html
{% extends 'navbar/navbar_base.html' %}
{% block navbar_nav %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'admin:index' %}">Admin Dashboard</a>
</li>
{% endblock %}
{% block navbar_text %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'users:change_password'%}">Change Password</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'users:logout'%}">Logout</a>
</li>
{% endblock %}

templates/navbar/employer_navbar.html
{% extends 'navbar/navbar_base.html' %}
{% block navbar_nav %}
<li class="nav-item">
  <a class="nav-link" href="#">Dashboard</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Post a Job</a>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Exam
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="#">Create Exam</a>
    <a class="dropdown-item" href="#">Edit Exams</a>
    <a class="dropdown-item" href="#">Exam Results</a>
  </div>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Interviewer
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="#">Add Interviewer</a>
    <a class="dropdown-item" href="#">View Interviewers</a>
  </div>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Interview
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <a class="dropdown-item" href="#">Create Interview</a>
    <a class="dropdown-item" href="#">View Interviews</a>
  </div>
</li>
{% endblock %}
{% block navbar_text %}
<li class="nav-item active">
  <a class="nav-link" href="#">Company Profile</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'users:change_password'%}">Change Password</a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="{% url 'users:logout'%}">Logout</a>
</li>
{% endblock %}

templates/navbar/interviewer_navbar.html
{% extends 'navbar/navbar_base.html' %}
{% block navbar_nav %}
<li class="nav-item">
  <a class="nav-link" href="#">Dashboard</a>
</li>
{% endblock %}
{% block navbar_text %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'users:change_password'%}">Change Password</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'users:logout'%}">Logout</a>
</li>
{% endblock %}

templates/navbar/job_seeker_navbar.html
{% extends 'navbar/navbar_base.html' %}
{% block navbar_nav %}
<li class="nav-item">
  <a class="nav-link" href="#">Find Jobs</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Applications</a>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Exam
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="#">Give Exam</a>
    <a class="dropdown-item" href="#">View Results</a>
  </div>
</li>
{% endblock %}
{% block navbar_text %}
<li class="nav-item">
  <a class="nav-link" href="#">My Profile</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'users:change_password'%}">Change Password</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'users:logout'%}">Logout</a>
</li>
{% endblock %}

templates/navbar/navbar_base.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Jobportal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% block navbar_nav %}{% endblock %}
    </ul>
    <span class="navbar-text py-0">
      <ul class="navbar-nav ">
        {% block navbar_text %}{% endblock %}
      </ul>
    </span>
  </div>
</nav>
<script id="navbar_script" type="text/javascript">
    // highlighting current url as active in navbar
    document.addEventListener('DOMContentLoaded', (event) => {
        let active_path = window.location.pathname;
        // clearing active nav-items
        let nav_items = document.querySelectorAll('.navbar>.navbar-collapse .nav-item');
        for (nav_item of nav_items) {
            nav_item.classList.remove('active');
            if (nav_item.classList.contains('dropdown')) {
                let nav_item_dropdown_items = nav_item.querySelectorAll('.dropdown-menu>.dropdown-item');
                for (dropdown_item of nav_item_dropdown_items) {
                    dropdown_item.classList.remove('active');
                }
            }
        }
        // highlighting the nav-item
        let curr_nav_item = document.querySelector(`.navbar>.navbar-collapse .nav-link[href='${active_path}']`)
        if (curr_nav_item) {
            curr_nav_item.classList.add('active');
        }
    });
</script>

templates/navbar/visitor_navbar.html
{% extends 'navbar/navbar_base.html' %}
{% block navbar_nav %}
<li class="nav-item">
    <a class="nav-link" href="#">Find jobs</a>
</li>
{% endblock %}
{% block navbar_text %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
</li>
{% endblock %}