job_portal_final/urls.py
from django.contrib import admin
from django.urls import path, include
import pages.views as pages_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', pages_views.home_view, name='home'),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import *
from .views import *

app_name = 'users'
urlpatterns = [
    path('signup', signup_view, name='signup'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('change-email', change_email_view, name='change_email'),
    path('change-password', auth_views.PasswordChangeView.as_view(
        template_name='users/change_password.html',
        success_url='change-password/done',
        form_class=CustomPasswordChangeForm,
    ), name='change_password'),
    path('change-password/done', auth_views.PasswordChangeDoneView.as_view(template_name='users/change_password_done.html'), name='change_password_done'),
    path('reset-password', auth_views.PasswordResetView.as_view(
        template_name='users/reset_password.html',
        email_template_name='users/reset_password_email.html',
        success_url='reset-password/done',
        form_class=CustomPasswordResetForm,
    ), name='reset_password'),
    path('reset-password/done', auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_done.html'), name='reset_password_done'),
    path('reset-password-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/reset_password_confirm.html',
        success_url='/users/reset-password-complete',
        form_class=CustomSetPasswordForm,
    ), name='reset_password_confirm'),
    path('reset-password-complete', auth_views.PasswordResetCompleteView.as_view(template_name='users/reset_password_complete.html'), name='reset_password_complete'),
]

users/models.py
from django.db import models
from django.db.models.deletion import CASCADE, PROTECT
from django.contrib.auth.models import BaseUserManager, PermissionsMixin, AbstractBaseUser
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.core import validators
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from job_portal_final.custom_fields import *

# Create your models here.
class Role_master(models.Model):
    role_name = UpperCharField(
        max_length=20,
        unique=True,
        validators=[
            validators.RegexValidator(
                regex=r'^(?! )(?:[a-zA-Z]| (?! ))+(?<! )$',
                message='Role name must contain only letters and spaces.'
            ),
        ],
        error_messages={
            'unique': _('A role with that name already exists.'),
        }
    )

    def __str__(self):
        return self.role_name

    class Meta:
        verbose_name = 'Role'

class User_accountManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set.')
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        admin_role = Role_master.objects.get(role_name='ADMIN') # make sure ADMIN role exists
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('role', admin_role)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('role') is not admin_role:
            raise ValueError('Superuser must belong to ADMIN role.')
        return self.create_user(email, password, **extra_fields)

class User_account(AbstractBaseUser, PermissionsMixin):
    email = UpperEmailField(
        _('email address'),
        unique=True,
        error_messages={
            'unique': _('A user with that email address already exists.'),
        },
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into the admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    role = models.ForeignKey(
        Role_master,
        on_delete=PROTECT,
        help_text=_('Designates what role the user belongs to.'),
    )
    related_employer = models.ForeignKey(
        'employers.Employer_profile',
        blank=True,
        null=True,
        default=None,
        on_delete=models.CASCADE,
        help_text=_('For relating user of interviewer role to an employer profile.')
    )
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = User_accountManager()

    def clean(self):
        error_dict = {}
        if hasattr(self, 'role'):
            # NOTE: checking based on predefined role_name
            # checking is_staff and is_superuser
            if self.role.role_name == 'ADMIN':
                if not self.is_staff:
                    error_dict['is_staff'] = 'User of admin role must have is_staff equal to true.'
                if not self.is_superuser:
                    error_dict['is_superuser'] = 'User of admin role must have is_superuser equal to true.'
            elif self.role.role_name == 'STAFF':
                if not self.is_staff:
                    error_dict['is_staff'] = 'User of staff role must have is_staff equal to true.'
                if self.is_superuser:
                    error_dict['is_superuser'] = 'Invalid permissions for user belonging to staff role.'
            else:
                if self.is_staff:
                    error_dict['is_staff'] = 'Invalid permissions for user.'
                if self.is_superuser:
                    error_dict['is_superuser'] = 'Invalid permissions for user.'

            # checking related_employer
            if self.role.role_name == 'INTERVIEWER' and self.related_employer is None:
                error_dict['related_employer'] = 'Related employer must be provided for user belonging interviewer role.'
            elif self.role.role_name != 'INTERVIEWER' and self.related_employer is not None:
                error_dict['related_employer'] = 'Related employer can only be set for user belonging interviewer role.'

        raise ValidationError(error_dict)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.email.lower()

users/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.utils.translation import gettext, gettext_lazy as _

class CustomPasswordChangeForm(auth_forms.PasswordChangeForm):
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True, 'class': 'form-control'}),
    )
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'pattern': '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,20}$', 'title': 'Password must be 8-20 characters long, contain lowercase and uppercase letters, numbers and special characters (@$!%*?&), and must not contain spaces or other characters'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Retype your new password', 'oninput': 'check_password(this)'}),
    )

class CustomPasswordResetForm(auth_forms.PasswordResetForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class': 'form-control', 'placeholder': 'username@domain.com', 'pattern': '^[\w\.\+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\.\-]+$', 'title': 'username@domain.com'})
    )

class CustomSetPasswordForm(auth_forms.SetPasswordForm):
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'pattern': '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,20}$', 'title': 'Password must be 8-20 characters long, contain lowercase and uppercase letters, numbers and special characters (@$!%*?&), and must not contain spaces or other characters'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Retype your new password', 'oninput': 'check_password(this)'}),
    )

users/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import auth, messages
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils import timezone
from .models import *

# Create your views here.
@user_passes_test(lambda user: not user.is_authenticated, login_url='/', redirect_field_name=None)
def signup_view(request):
    context = {
        'form': {'role': request.GET.get('role'), },
    }
    if request.method == 'POST':
        role_input = request.POST.get('role')
        email_input = request.POST.get('email')
        password_input = request.POST.get('password')
        confirm_password_input = request.POST.get('confirm_password')
        context['form'] = {
            'role': role_input,
            'email': email_input,
        }
        if role_input == "JOB SEEKER" or role_input == "EMPLOYER":
            role = Role_master.objects.get(role_name = role_input)
            try:
                if password_input == confirm_password_input:
                    user_account = User_account(email=email_input, role=role)
                    try:
                        validate_password(password_input, user_account)
                    except ValidationError as e:
                        raise ValidationError({'password': e}) # converting error_list to error_dict with key 'password'
                    user_account.set_password(password_input)
                    user_account.full_clean()
                    user_account.save()
                    user_account = auth.authenticate(request, email=email_input, password=password_input)
                    auth.login(request, user_account)
                    user_account.email_user('Account Created!', 'You have been successfully registered to job portal.')
                    if user_account.role.role_name == 'JOB SEEKER':
                        return HttpResponse('personal details')
                    else:
                        return HttpResponse('employer details')
                else:
                    raise ValidationError({'confirm_password': 'Password and confirm password don\'t match.'})
            except ValidationError as e:
                if hasattr(e, 'error_dict'):
                    context['errors'] = e.message_dict.items()
                else:
                    context['errors'] = [('__all__', e), ]
        else:
            context['errors'] = [('role', ['Please select either job seeker or employer.'])]
    return render(request, 'users/signup.html', context)

def login_view(request):
    context = {}
    if request.method == 'POST':
        email_input = request.POST.get('email')
        password_input = request.POST.get('password')
        user_account = auth.authenticate(request, email=email_input, password=password_input)
        if user_account is not None:
            auth.login(request, user_account)
            redirect_url = request.GET.get('next')
            if redirect_url:
                return redirect(redirect_url)
            else:
                if user_account.role.role_name == "ADMIN" or user_account.role.role_name == "STAFF":
                    return redirect('/admin/')
                else:
                    return redirect('/')
        else:
            context['errors'] = [('__all__', ['Invalid email or password!']), ]
    return render(request, 'users/login.html', context)

def logout_view(request):
    auth.logout(request)
    return redirect('/')

@login_required
def change_email_view(request):
    context = {}
    if request.method == 'POST':
        try:
            email_input = request.POST.get('email').strip().lower()
            user_account = request.user
            curr_email = user_account.email.lower()
            if email_input != curr_email:
                user_account.email = email_input
                user_account.full_clean()
                User_account.objects.get(id=request.user.id).email_user('Email Changed!', 'Your registered email has been changed from {} to {}.'.format(curr_email, user_account.email.lower()))
                user_account.save()
                messages.success(request, 'Email changed successfully!')
                return HttpResponse('home')
            else:
                raise ValidationError({'email': 'New email can\'t be same as current email.'})
        except ValidationError as e:
            if hasattr(e, 'error_dict'):
                context['errors'] = e.message_dict.items()
            else:
                context['errors'] = [('__all__', e), ]
    return render(request, 'users/change_email.html', context)

users/templates/users/change_email.html
{% extends 'form_card.html' %}
{% block title %}
Change Email
{% endblock title %}
{% block form_title %}
Change Email
{% endblock form_title %}
{% block form %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="new_email_input">New email:</label>
        <input id="new_email_input" type="email" name="email" class="form-control" placeholder="username@domain.com" pattern="^[\w\.\+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\.\-]+$" title="username@domain.com" required />
    </div>
    <a href="{% url 'home' %}"  class="btn btn-warning">Cancel</a>
    <input type="submit" class="btn btn-success" value="Change Email" />
</form>
{% endblock form %}

users/templates/users/change_password.html
{% extends 'form_card.html' %}
{% block title %}
Change Password
{% endblock title %}
{% block form_title %}
Change Password
{% endblock form_title %}
{% block form %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form.old_password.label_tag }}
        <div class="input-group">
            {{ form.old_password }}
            <div class="input-group-append">
                <span class="input-group-text" onclick="this.parentElement.previousElementSibling.type = (this.parentElement.previousElementSibling.type == 'password' && 'text') || 'password'; this.children[0].classList.contains('bi-eye-fill')? this.children[0].classList.replace('bi-eye-fill', 'bi-eye-slash-fill') : this.children[0].classList.replace('bi-eye-slash-fill', 'bi-eye-fill');">
                    <i class="bi-eye-fill" ></i>
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        {{ form.new_password1.label_tag }}
        <div class="input-group">
            {{ form.new_password1 }}
            <div class="input-group-append">
                <span class="input-group-text" onclick="this.parentElement.previousElementSibling.type = (this.parentElement.previousElementSibling.type == 'password' && 'text') || 'password'; this.children[0].classList.contains('bi-eye-fill')? this.children[0].classList.replace('bi-eye-fill', 'bi-eye-slash-fill') : this.children[0].classList.replace('bi-eye-slash-fill', 'bi-eye-fill');">
                    <i class="bi-eye-fill" ></i>
                </span>
            </div>
            <small class="form-text text-muted">
            Your password must be 8-20 characters long, contain lowercase and uppercase letters, numbers and special characters (@$!%*?&), and must not contain spaces or other characters.
            </small>
        </div>
    </div>
    <div class="form-group">
        {{ form.new_password2.label_tag }}
        <div class="input-group">
            {{ form.new_password2 }}
            <div class="input-group-append">
                <span class="input-group-text" onclick="this.parentElement.previousElementSibling.type = (this.parentElement.previousElementSibling.type == 'password' && 'text') || 'password'; this.children[0].classList.contains('bi-eye-fill')? this.children[0].classList.replace('bi-eye-fill', 'bi-eye-slash-fill') : this.children[0].classList.replace('bi-eye-slash-fill', 'bi-eye-fill');">
                    <i class="bi-eye-fill" ></i>
                </span>
            </div>
        </div>
    </div>
    <a href="{% url 'home' %}" class="btn btn-warning">Cancel</a>
    <input type="submit" class="btn btn-success" value="Change Password"/>
</form>
{% endblock form %}
{% block error_list %}
    {{ form.errors }}
{% endblock error_list %}
{% block script %}
var error_list = document.getElementsByClassName('errorlist')[0];
{{ block.super }}
function check_password(new_password2) {
    let new_password1 = document.getElementById('id_new_password1');
    if (new_password1.value != new_password2.value) {
        new_password2.setCustomValidity('Password and confirm password don\'t match.');
    }
    else {
        new_password2.setCustomValidity('');
    }
}
{% endblock script %}

users/templates/users/change_password_done.html
{% extends 'base.html' %}
{% block title %}
Password Change Successful
{% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card my-5">
                <h4 class="card-header text-center">
                    Password Change Successful
                </h4>
                <div class="card-body text-center">
                    <i class="bi-shield-fill-check mr-3"></i>Password has been changed successfully!
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'form_card.html' %}
{% block title %}
Login
{% endblock title %}
{% block form_title %}
Login
{% endblock form_title %}
{% block form %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="email_input">Email:</label>
        <input id="email_input" type="email" name="email" class="form-control" placeholder="username@domain.com" pattern="^[\w\.\+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\.\-]+$" title="username@domain.com" required />
    </div>
    <div class="form-group">
        <label for="password_input">Password:</label>
        <div class="input-group">
            <input id="password_input" type="password" name="password" class="form-control" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,20}$" title="Password must be 8-20 characters long, contain lowercase and uppercase letters, numbers and special characters (@$!%*?&), and must not contain spaces or other characters" required />
            <div class="input-group-append">
                <span class="input-group-text" onclick="this.parentElement.previousElementSibling.type = (this.parentElement.previousElementSibling.type == 'password' && 'text') || 'password'; this.children[0].classList.contains('bi-eye-fill')? this.children[0].classList.replace('bi-eye-fill', 'bi-eye-slash-fill') : this.children[0].classList.replace('bi-eye-slash-fill', 'bi-eye-fill');">
                    <i class="bi-eye-fill" ></i>
                </span>
            </div>
        </div>
        <small class="form-text text-muted">
        Your password must be 8-20 characters long, contain lowercase and uppercase letters, numbers and special characters (@$!%*?&), and must not contain spaces or other characters.
        </small>
    </div>
    <div class="form-group">
        <a href="{% url 'users:reset_password' %}">Forgot Your password?</a>
        <br>
        New to job portal? <a href="{% url 'users:signup' %}">Sign Up</a>
    </div>
    <a href="{% url 'home' %}"  class="btn btn-warning">Cancel</a>
    <input type="submit" class="btn btn-success" value="Login" />
</form>
{% endblock form %}

users/templates/users/reset_password.html
{% extends 'form_card.html' %}
{% block title %}
Forgot Password
{% endblock title %}
{% block form_title %}
Forgot Password?
{% endblock form_title %}
{% block form %}
<form method="post">
    {% csrf_token %}
    {{ form.email.label_tag }}
    <div class="form-group">
        {{ form.email }}
    </div>
    <a href="{% url 'home' %}" class="btn btn-warning">Cancel</a>
    <input type="submit" class="btn btn-success" value="Send Link"/>
</form>
{% endblock form %}
{% block error_list %}
    {{ form.errors }}
{% endblock error_list %}
{% block script %}
var error_list = document.getElementsByClassName('errorlist')[0];
{{ block.super }}
{% endblock script %}

users/templates/users/reset_password_complete.html
{% extends 'base.html' %}
{% block title %}
Password Reset Successful
{% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card my-5">
                <h4 class="card-header text-center">
                    Password Reset Successful
                </h4>
                <div class="card-body text-center">
                    <i class="bi-shield-fill-check mr-3"></i>Password has been changed successfully!
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/reset_password_confirm.html
{% extends 'form_card.html' %}
{% block title %}
Reset Password
{% endblock title %}
{% block form_title %}
    {% if validlink %}
    Reset Password
    {% else %}
    Invalid Password Reset Link
    {% endif %}
{% endblock form_title %}
{% block form %}
    {% if validlink %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.new_password1.label_tag }}
            <div class="input-group">
                {{ form.new_password1 }}
                <div class="input-group-append">
                    <span class="input-group-text" onclick="this.parentElement.previousElementSibling.type = (this.parentElement.previousElementSibling.type == 'password' && 'text') || 'password'; this.children[0].classList.contains('bi-eye-fill')? this.children[0].classList.replace('bi-eye-fill', 'bi-eye-slash-fill') : this.children[0].classList.replace('bi-eye-slash-fill', 'bi-eye-fill');">
                        <i class="bi-eye-fill" ></i>
                    </span>
                </div>
                <small class="form-text text-muted">
                Your password must be 8-20 characters long, contain lowercase and uppercase letters, numbers and special characters (@$!%*?&), and must not contain spaces or other characters.
                </small>
            </div>
        </div>
        <div class="form-group">
            {{ form.new_password2.label_tag }}
            <div class="input-group">
                {{ form.new_password2 }}
                <div class="input-group-append">
                    <span class="input-group-text" onclick="this.parentElement.previousElementSibling.type = (this.parentElement.previousElementSibling.type == 'password' && 'text') || 'password'; this.children[0].classList.contains('bi-eye-fill')? this.children[0].classList.replace('bi-eye-fill', 'bi-eye-slash-fill') : this.children[0].classList.replace('bi-eye-slash-fill', 'bi-eye-fill');">
                        <i class="bi-eye-fill" ></i>
                    </span>
                </div>
            </div>
        </div>
        <a href="#" class="btn btn-warning">Cancel</a>
        <input type="submit" class="btn btn-success" value="Reset Password"/>
    </form>
    {% else %}
    <div class="text-center mx-auto">
        <i class="bi-shield-fill-exclamation mr-3"></i>Password reset link provided was incorrect or it has already been used!
    </div>
    {% endif %}
{% endblock form %}
{% block error_list %}
    {{ form.errors }}
{% endblock error_list %}
{% block script %}
var error_list = document.getElementsByClassName('errorlist')[0];
{{ block.super }}
function check_password(new_password2) {
    let new_password1 = document.getElementById('id_new_password1');
    if (new_password1.value != new_password2.value) {
        new_password2.setCustomValidity('Password and confirm password don\'t match.');
    }
    else {
        new_password2.setCustomValidity('');
    }
}
{% endblock script %}

users/templates/users/reset_password_done.html
{% extends 'base.html' %}
{% block title %}
Password Reset Link Sent
{% endblock title %}
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card my-5">
                <h4 class="card-header text-center">
                    Password Reset Link Sent
                </h4>
                <div class="card-body text-center">
                    <i class="bi-envelope-check-fill mr-3"></i>Password reset link should have been sent to your email address!
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:reset_password_confirm' uidb64=uid token=token %}
{% endblock %}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/signup.html
    {% extends 'form_card.html' %}
{% block title %}
Sign Up
{% endblock title %}
{% block style %}
{{ block.super }}
input[type="radio"]:checked + label {
    color: #0056b3;
    font-weight: bold;
}
{% endblock style %}
{% block form_title %}
    Sign Up
{% endblock form_title %}
{% block form %}
<form id="signup_form" method="post">
    {% csrf_token %}
    <div class="form-group text-center">
        <div class="custom-control custom-radio custom-control-inline">
            <input id="job_seeker_role_input" type="radio" name="role" value="JOB SEEKER" class="custom-control-input" required {% if not form.role or form.role == 'JOB SEEKER' %}checked{% endif %}>
            <label for="job_seeker_role_input" class="custom-control-label">Job Seeker</label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
            <input id="employer_role_input" type="radio" name="role" value="EMPLOYER" class="custom-control-input" required {% if form.role == 'EMPLOYER' %}checked{% endif %}>
            <label for="employer_role_input" class="custom-control-label">Employer</label>
        </div>
    </div>
    <div class="form-group">
        <label for="email_input">Email:</label>
        <input id="email_input" type="email" name="email" value="{{ form.email }}" class="form-control" placeholder="username@domain.com" pattern="^[\w\.\+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\.\-]+$" title="username@domain.com" required />
    </div>
    <div class="form-group">
        <label for="password_input">Password:</label>
        <div class="input-group">
            <input id="password_input" type="password" name="password" class="form-control" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,20}$" title="Password must be 8-20 characters long, contain lowercase and uppercase letters, numbers and special characters (@$!%*?&), and must not contain spaces or other characters" required />
            <div class="input-group-append">
                <span class="input-group-text" onclick="this.parentElement.previousElementSibling.type = (this.parentElement.previousElementSibling.type == 'password' && 'text') || 'password'; this.children[0].classList.contains('bi-eye-fill')? this.children[0].classList.replace('bi-eye-fill', 'bi-eye-slash-fill') : this.children[0].classList.replace('bi-eye-slash-fill', 'bi-eye-fill');">
                    <i class="bi-eye-fill" ></i>
                </span>
            </div>
        </div>
        <small class="form-text text-muted">
        Your password must be 8-20 characters long, contain lowercase and uppercase letters, numbers and special characters (@$!%*?&), and must not contain spaces or other characters.
        </small>
    </div>
    <div class="form-group">
        <label>Confirm password:</label>
        <div class="input-group">
            <input id="confirm_password_input" type="password" name="confirm_password" class="form-control" oninput="check_password(this)" required />
            <div class="input-group-append">
                <span class="input-group-text" onclick="this.parentElement.previousElementSibling.type = (this.parentElement.previousElementSibling.type == 'password' && 'text') || 'password'; this.children[0].classList.contains('bi-eye-fill')? this.children[0].classList.replace('bi-eye-fill', 'bi-eye-slash-fill') : this.children[0].classList.replace('bi-eye-slash-fill', 'bi-eye-fill');">
                    <i class="bi-eye-fill" ></i>
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        Already have an account? <a href="{% url 'users:login' %}">Login</a>
    </div>
    <a href="{% url 'home' %}" class="btn btn-warning">Cancel</a>
    <input type="submit" class="btn btn-success" value="Next"/>
</form>
{% endblock form %}
{% block script %}
{{ block.super }}
function check_password(confirm_password_input) {
    let password_input = document.getElementById('password_input');
    if (password_input.value != confirm_password_input.value) {
        confirm_password_input.setCustomValidity('Password and confirm password don\'t match.');
    }
    else {
        confirm_password_input.setCustomValidity('');
    }
}
{% endblock script %}